---
- hosts: mywebserver
  become: yes 
  tasks:
  - name: install apache2 on redhat server  
    yum:
     name: "{{nywebpack}}"
     state: present 
  - name: start apche2 service 
    service:
     name: "{{nywebpack}}" 
     state: started 
