---
- hosts: all 
  become: yes 
  tasks:
  - name: stop apche2 service 
    service:
     name: "{{nywebpack}}"
     state: stopped 
  - name: uninstall   apche2
    yum:
     name: "{{nywebpack}}" 
     state: absent 
