---
- hosts: mywebservers
  become: yes 
  tasks:
  - name: install apache2 on redhat server  
    yum:
     name: "{{mywebserverpack}}"
     state: present 
  - name: start apche2 service 
    service:
     name: "{{mywebserverpack}}" 
     state: started 
