---  
-  hosts: debug 
   become: yes 
   tasks: 
   - name: display output of command 
     command: uname -r 
     register: myvariable 
   - name: i want to display output 
     debug: 
      msg: "{{myvariable}}"     