---
- hosts: mywebservers
  become: yes  
  gather_facts: yes
  tasks:
  - name:  install git 
    yum:
     name: "{{mywebserverpack}}"  
     state: present 
  - name:  install httpd 
    yum: 
     name: "{{mywebpack}}"    
     state: present 
